<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AmongUs3D>$(MSBuildThisFileDirectory)..\..\..\..\..\Program Files (x86)\Steam\steamapps\common\Among Us 3D</AmongUs3D>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(AmongUs3D)\MelonLoader\net6\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppFusion.Addressables">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppFusion.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppFusion.Common">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppFusion.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppFusion.Realtime">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppFusion.Realtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppFusion.Runtime">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppFusion.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppFusion.Scripts">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppFusion.Scripts.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppFusion.Sockets">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppFusion.Sockets.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>$(AmongUs3D)\MelonLoader\net6\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Generator">
      <HintPath>$(AmongUs3D)\MelonLoader\net6\Il2CppInterop.Generator.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.HarmonySupport">
      <HintPath>$(AmongUs3D)\MelonLoader\net6\Il2CppInterop.HarmonySupport.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(AmongUs3D)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPhoton3Unity3D">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppPhoton3Unity3D.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPhotonRealtime">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppPhotonRealtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPhotonVoice">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppPhotonVoice.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPhotonVoice.API">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppPhotonVoice.API.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppPhotonVoice.Fusion">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppPhotonVoice.Fusion.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Airlock">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Airlock.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Core">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Core.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.GlobalEvents">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.GlobalEvents.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.LightTween">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.LightTween.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.LightUI">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.LightUI.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Platform">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Platform.Airlock3D">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.Airlock3D.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Platform.Oculus">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.Oculus.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Platform.QADebug">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.QADebug.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Platform.SimulatedXR">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.SimulatedXR.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Platform.Steam">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Platform.Steam.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.PlayerLoops">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.PlayerLoops.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.SkuBuild">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.SkuBuild.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.SkuBuild.Oculus">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.SkuBuild.Oculus.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.SkuBuild.Steam">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.SkuBuild.Steam.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.SoundCore">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.SoundCore.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.VAT">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.VAT.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSG.Vignettitor">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\Il2CppSG.Vignettitor.dll</HintPath>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>$(AmongUs3D)\MelonLoader\net6\MelonLoader.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(AmongUs3D)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>